sudo: false

language: node_js

node_js:
  - "stable"

env:
  global:
    CODECOV_TOKEN="ba7ffd80-ff85-4a5f-9ae6-bd6acede2e74"

cache:
  directories:
    - "node_modules"

services:
  - postgresql

install:
  - npm install

script:
  - npm test

after_success:
    - bash <(curl -s https://codecov.io/bash)

notification:
  false
